/**
 * Lista internacional completa de códigos de marcación (ITU-T E.164)
 * Ordenados alfabéticamente por nombre en español.
 */
export interface InternationalPhoneCode {
  code: string;     // ISO 3166-1 alpha-2
  dialCode: string; // e.g. '+506'
  name: string;     // Nombre en español
}

export const INTERNATIONAL_PHONE_CODES: InternationalPhoneCode[] = [
  { code: 'AF', dialCode: '+93',   name: 'Afganistán' },
  { code: 'AL', dialCode: '+355',  name: 'Albania' },
  { code: 'DE', dialCode: '+49',   name: 'Alemania' },
  { code: 'DZ', dialCode: '+213',  name: 'Algeria' },
  { code: 'AD', dialCode: '+376',  name: 'Andorra' },
  { code: 'AO', dialCode: '+244',  name: 'Angola' },
  { code: 'AI', dialCode: '+1264', name: 'Anguila' },
  { code: 'AG', dialCode: '+1268', name: 'Antigua y Barbuda' },
  { code: 'SA', dialCode: '+966',  name: 'Arabia Saudita' },
  { code: 'AR', dialCode: '+54',   name: 'Argentina' },
  { code: 'AM', dialCode: '+374',  name: 'Armenia' },
  { code: 'AW', dialCode: '+297',  name: 'Aruba' },
  { code: 'AU', dialCode: '+61',   name: 'Australia' },
  { code: 'AT', dialCode: '+43',   name: 'Austria' },
  { code: 'AZ', dialCode: '+994',  name: 'Azerbaiyán' },
  { code: 'BS', dialCode: '+1242', name: 'Bahamas' },
  { code: 'BH', dialCode: '+973',  name: 'Bahréin' },
  { code: 'BD', dialCode: '+880',  name: 'Bangladés' },
  { code: 'BB', dialCode: '+1246', name: 'Barbados' },
  { code: 'BE', dialCode: '+32',   name: 'Bélgica' },
  { code: 'BZ', dialCode: '+501',  name: 'Belice' },
  { code: 'BJ', dialCode: '+229',  name: 'Benín' },
  { code: 'BM', dialCode: '+1441', name: 'Bermudas' },
  { code: 'BY', dialCode: '+375',  name: 'Bielorrusia' },
  { code: 'BO', dialCode: '+591',  name: 'Bolivia' },
  { code: 'BA', dialCode: '+387',  name: 'Bosnia y Herzegovina' },
  { code: 'BW', dialCode: '+267',  name: 'Botsuana' },
  { code: 'BR', dialCode: '+55',   name: 'Brasil' },
  { code: 'BN', dialCode: '+673',  name: 'Brunéi' },
  { code: 'BG', dialCode: '+359',  name: 'Bulgaria' },
  { code: 'BF', dialCode: '+226',  name: 'Burkina Faso' },
  { code: 'BI', dialCode: '+257',  name: 'Burundi' },
  { code: 'BT', dialCode: '+975',  name: 'Bután' },
  { code: 'CV', dialCode: '+238',  name: 'Cabo Verde' },
  { code: 'KH', dialCode: '+855',  name: 'Camboya' },
  { code: 'CM', dialCode: '+237',  name: 'Camerún' },
  { code: 'CA', dialCode: '+1',    name: 'Canadá' },
  { code: 'QA', dialCode: '+974',  name: 'Catar' },
  { code: 'TD', dialCode: '+235',  name: 'Chad' },
  { code: 'CL', dialCode: '+56',   name: 'Chile' },
  { code: 'CN', dialCode: '+86',   name: 'China' },
  { code: 'CY', dialCode: '+357',  name: 'Chipre' },
  { code: 'CO', dialCode: '+57',   name: 'Colombia' },
  { code: 'KM', dialCode: '+269',  name: 'Comoras' },
  { code: 'CG', dialCode: '+242',  name: 'Congo' },
  { code: 'CD', dialCode: '+243',  name: 'Congo (R. Dem.)' },
  { code: 'KP', dialCode: '+850',  name: 'Corea del Norte' },
  { code: 'KR', dialCode: '+82',   name: 'Corea del Sur' },
  { code: 'CI', dialCode: '+225',  name: 'Costa de Marfil' },
  { code: 'CR', dialCode: '+506',  name: 'Costa Rica' },
  { code: 'HR', dialCode: '+385',  name: 'Croacia' },
  { code: 'CU', dialCode: '+53',   name: 'Cuba' },
  { code: 'CW', dialCode: '+599',  name: 'Curazao' },
  { code: 'DK', dialCode: '+45',   name: 'Dinamarca' },
  { code: 'DM', dialCode: '+1767', name: 'Dominica' },
  { code: 'EC', dialCode: '+593',  name: 'Ecuador' },
  { code: 'EG', dialCode: '+20',   name: 'Egipto' },
  { code: 'SV', dialCode: '+503',  name: 'El Salvador' },
  { code: 'AE', dialCode: '+971',  name: 'Emiratos Árabes Unidos' },
  { code: 'ER', dialCode: '+291',  name: 'Eritrea' },
  { code: 'SK', dialCode: '+421',  name: 'Eslovaquia' },
  { code: 'SI', dialCode: '+386',  name: 'Eslovenia' },
  { code: 'ES', dialCode: '+34',   name: 'España' },
  { code: 'US', dialCode: '+1',    name: 'Estados Unidos' },
  { code: 'EE', dialCode: '+372',  name: 'Estonia' },
  { code: 'SZ', dialCode: '+268',  name: 'Esuatini' },
  { code: 'ET', dialCode: '+251',  name: 'Etiopía' },
  { code: 'PH', dialCode: '+63',   name: 'Filipinas' },
  { code: 'FI', dialCode: '+358',  name: 'Finlandia' },
  { code: 'FJ', dialCode: '+679',  name: 'Fiyi' },
  { code: 'FR', dialCode: '+33',   name: 'Francia' },
  { code: 'GA', dialCode: '+241',  name: 'Gabón' },
  { code: 'GM', dialCode: '+220',  name: 'Gambia' },
  { code: 'GE', dialCode: '+995',  name: 'Georgia' },
  { code: 'GH', dialCode: '+233',  name: 'Ghana' },
  { code: 'GI', dialCode: '+350',  name: 'Gibraltar' },
  { code: 'GD', dialCode: '+1473', name: 'Granada' },
  { code: 'GR', dialCode: '+30',   name: 'Grecia' },
  { code: 'GL', dialCode: '+299',  name: 'Groenlandia' },
  { code: 'GP', dialCode: '+590',  name: 'Guadalupe' },
  { code: 'GU', dialCode: '+1671', name: 'Guam' },
  { code: 'GT', dialCode: '+502',  name: 'Guatemala' },
  { code: 'GN', dialCode: '+224',  name: 'Guinea' },
  { code: 'GQ', dialCode: '+240',  name: 'Guinea Ecuatorial' },
  { code: 'GW', dialCode: '+245',  name: 'Guinea-Bisáu' },
  { code: 'GY', dialCode: '+592',  name: 'Guyana' },
  { code: 'GF', dialCode: '+594',  name: 'Guyana Francesa' },
  { code: 'HT', dialCode: '+509',  name: 'Haití' },
  { code: 'HN', dialCode: '+504',  name: 'Honduras' },
  { code: 'HK', dialCode: '+852',  name: 'Hong Kong' },
  { code: 'HU', dialCode: '+36',   name: 'Hungría' },
  { code: 'IN', dialCode: '+91',   name: 'India' },
  { code: 'ID', dialCode: '+62',   name: 'Indonesia' },
  { code: 'IQ', dialCode: '+964',  name: 'Irak' },
  { code: 'IR', dialCode: '+98',   name: 'Irán' },
  { code: 'IE', dialCode: '+353',  name: 'Irlanda' },
  { code: 'IS', dialCode: '+354',  name: 'Islandia' },
  { code: 'KY', dialCode: '+1345', name: 'Islas Caimán' },
  { code: 'FK', dialCode: '+500',  name: 'Islas Malvinas' },
  { code: 'MH', dialCode: '+692',  name: 'Islas Marshall' },
  { code: 'SB', dialCode: '+677',  name: 'Islas Salomón' },
  { code: 'TC', dialCode: '+1649', name: 'Islas Turcas y Caicos' },
  { code: 'VI', dialCode: '+1340', name: 'Islas Vírgenes (EE.UU.)' },
  { code: 'VG', dialCode: '+1284', name: 'Islas Vírgenes Brit.' },
  { code: 'IL', dialCode: '+972',  name: 'Israel' },
  { code: 'IT', dialCode: '+39',   name: 'Italia' },
  { code: 'JM', dialCode: '+1876', name: 'Jamaica' },
  { code: 'JP', dialCode: '+81',   name: 'Japón' },
  { code: 'JO', dialCode: '+962',  name: 'Jordania' },
  { code: 'KZ', dialCode: '+7',    name: 'Kazajistán' },
  { code: 'KE', dialCode: '+254',  name: 'Kenia' },
  { code: 'KG', dialCode: '+996',  name: 'Kirguistán' },
  { code: 'KI', dialCode: '+686',  name: 'Kiribati' },
  { code: 'KW', dialCode: '+965',  name: 'Kuwait' },
  { code: 'LA', dialCode: '+856',  name: 'Laos' },
  { code: 'LS', dialCode: '+266',  name: 'Lesoto' },
  { code: 'LV', dialCode: '+371',  name: 'Letonia' },
  { code: 'LB', dialCode: '+961',  name: 'Líbano' },
  { code: 'LR', dialCode: '+231',  name: 'Liberia' },
  { code: 'LY', dialCode: '+218',  name: 'Libia' },
  { code: 'LI', dialCode: '+423',  name: 'Liechtenstein' },
  { code: 'LT', dialCode: '+370',  name: 'Lituania' },
  { code: 'LU', dialCode: '+352',  name: 'Luxemburgo' },
  { code: 'MO', dialCode: '+853',  name: 'Macao' },
  { code: 'MG', dialCode: '+261',  name: 'Madagascar' },
  { code: 'MY', dialCode: '+60',   name: 'Malasia' },
  { code: 'MW', dialCode: '+265',  name: 'Malaui' },
  { code: 'MV', dialCode: '+960',  name: 'Maldivas' },
  { code: 'ML', dialCode: '+223',  name: 'Malí' },
  { code: 'MT', dialCode: '+356',  name: 'Malta' },
  { code: 'MA', dialCode: '+212',  name: 'Marruecos' },
  { code: 'MQ', dialCode: '+596',  name: 'Martinica' },
  { code: 'MU', dialCode: '+230',  name: 'Mauricio' },
  { code: 'MR', dialCode: '+222',  name: 'Mauritania' },
  { code: 'MX', dialCode: '+52',   name: 'México' },
  { code: 'FM', dialCode: '+691',  name: 'Micronesia' },
  { code: 'MD', dialCode: '+373',  name: 'Moldavia' },
  { code: 'MC', dialCode: '+377',  name: 'Mónaco' },
  { code: 'MN', dialCode: '+976',  name: 'Mongolia' },
  { code: 'ME', dialCode: '+382',  name: 'Montenegro' },
  { code: 'MS', dialCode: '+1664', name: 'Montserrat' },
  { code: 'MZ', dialCode: '+258',  name: 'Mozambique' },
  { code: 'MM', dialCode: '+95',   name: 'Myanmar' },
  { code: 'NA', dialCode: '+264',  name: 'Namibia' },
  { code: 'NR', dialCode: '+674',  name: 'Nauru' },
  { code: 'NP', dialCode: '+977',  name: 'Nepal' },
  { code: 'NI', dialCode: '+505',  name: 'Nicaragua' },
  { code: 'NE', dialCode: '+227',  name: 'Níger' },
  { code: 'NG', dialCode: '+234',  name: 'Nigeria' },
  { code: 'NO', dialCode: '+47',   name: 'Noruega' },
  { code: 'NC', dialCode: '+687',  name: 'Nueva Caledonia' },
  { code: 'NZ', dialCode: '+64',   name: 'Nueva Zelanda' },
  { code: 'OM', dialCode: '+968',  name: 'Omán' },
  { code: 'NL', dialCode: '+31',   name: 'Países Bajos' },
  { code: 'PK', dialCode: '+92',   name: 'Pakistán' },
  { code: 'PW', dialCode: '+680',  name: 'Palaos' },
  { code: 'PS', dialCode: '+970',  name: 'Palestina' },
  { code: 'PA', dialCode: '+507',  name: 'Panamá' },
  { code: 'PG', dialCode: '+675',  name: 'Papúa Nueva Guinea' },
  { code: 'PY', dialCode: '+595',  name: 'Paraguay' },
  { code: 'PE', dialCode: '+51',   name: 'Perú' },
  { code: 'PF', dialCode: '+689',  name: 'Polinesia Francesa' },
  { code: 'PL', dialCode: '+48',   name: 'Polonia' },
  { code: 'PT', dialCode: '+351',  name: 'Portugal' },
  { code: 'PR', dialCode: '+1787', name: 'Puerto Rico' },
  { code: 'GB', dialCode: '+44',   name: 'Reino Unido' },
  { code: 'CF', dialCode: '+236',  name: 'República Centroafricana' },
  { code: 'CZ', dialCode: '+420',  name: 'República Checa' },
  { code: 'DO', dialCode: '+1809', name: 'República Dominicana' },
  { code: 'MK', dialCode: '+389',  name: 'República de Macedonia' },
  { code: 'RE', dialCode: '+262',  name: 'Reunión' },
  { code: 'RW', dialCode: '+250',  name: 'Ruanda' },
  { code: 'RO', dialCode: '+40',   name: 'Rumanía' },
  { code: 'RU', dialCode: '+7',    name: 'Rusia' },
  { code: 'WS', dialCode: '+685',  name: 'Samoa' },
  { code: 'AS', dialCode: '+1684', name: 'Samoa Americana' },
  { code: 'KN', dialCode: '+1869', name: 'San Cristóbal y Nieves' },
  { code: 'SM', dialCode: '+378',  name: 'San Marino' },
  { code: 'PM', dialCode: '+508',  name: 'San Pedro y Miquelón' },
  { code: 'VC', dialCode: '+1784', name: 'San Vicente y las Granadinas' },
  { code: 'SH', dialCode: '+290',  name: 'Santa Elena' },
  { code: 'LC', dialCode: '+1758', name: 'Santa Lucía' },
  { code: 'ST', dialCode: '+239',  name: 'Santo Tomé y Príncipe' },
  { code: 'SN', dialCode: '+221',  name: 'Senegal' },
  { code: 'RS', dialCode: '+381',  name: 'Serbia' },
  { code: 'SC', dialCode: '+248',  name: 'Seychelles' },
  { code: 'SL', dialCode: '+232',  name: 'Sierra Leona' },
  { code: 'SG', dialCode: '+65',   name: 'Singapur' },
  { code: 'SY', dialCode: '+963',  name: 'Siria' },
  { code: 'SO', dialCode: '+252',  name: 'Somalia' },
  { code: 'LK', dialCode: '+94',   name: 'Sri Lanka' },
  { code: 'ZA', dialCode: '+27',   name: 'Sudáfrica' },
  { code: 'SD', dialCode: '+249',  name: 'Sudán' },
  { code: 'SS', dialCode: '+211',  name: 'Sudán del Sur' },
  { code: 'SE', dialCode: '+46',   name: 'Suecia' },
  { code: 'CH', dialCode: '+41',   name: 'Suiza' },
  { code: 'SR', dialCode: '+597',  name: 'Surinam' },
  { code: 'TH', dialCode: '+66',   name: 'Tailandia' },
  { code: 'TW', dialCode: '+886',  name: 'Taiwán' },
  { code: 'TZ', dialCode: '+255',  name: 'Tanzania' },
  { code: 'TJ', dialCode: '+992',  name: 'Tayikistán' },
  { code: 'TL', dialCode: '+670',  name: 'Timor Oriental' },
  { code: 'TG', dialCode: '+228',  name: 'Togo' },
  { code: 'TO', dialCode: '+676',  name: 'Tonga' },
  { code: 'TT', dialCode: '+1868', name: 'Trinidad y Tobago' },
  { code: 'TN', dialCode: '+216',  name: 'Túnez' },
  { code: 'TM', dialCode: '+993',  name: 'Turkmenistán' },
  { code: 'TR', dialCode: '+90',   name: 'Turquía' },
  { code: 'TV', dialCode: '+688',  name: 'Tuvalu' },
  { code: 'UA', dialCode: '+380',  name: 'Ucrania' },
  { code: 'UG', dialCode: '+256',  name: 'Uganda' },
  { code: 'UY', dialCode: '+598',  name: 'Uruguay' },
  { code: 'UZ', dialCode: '+998',  name: 'Uzbekistán' },
  { code: 'VU', dialCode: '+678',  name: 'Vanuatu' },
  { code: 'VE', dialCode: '+58',   name: 'Venezuela' },
  { code: 'VN', dialCode: '+84',   name: 'Vietnam' },
  { code: 'YE', dialCode: '+967',  name: 'Yemen' },
  { code: 'DJ', dialCode: '+253',  name: 'Yibuti' },
  { code: 'ZM', dialCode: '+260',  name: 'Zambia' },
  { code: 'ZW', dialCode: '+263',  name: 'Zimbabue' },
];

/**
 * Extrae el código de marcación y los dígitos de un número de teléfono almacenado.
 * Formato esperado: "+506 87654321" → { dialCode: "+506", digits: "87654321" }
 */
export function parseStoredPhone(phone: string): { dialCode: string; digits: string } {
  if (!phone) return { dialCode: '+1', digits: '' };
  const trimmed = phone.trim();
  if (!trimmed.startsWith('+')) return { dialCode: '+1', digits: trimmed.replace(/\D/g, '') };
  const spaceIdx = trimmed.indexOf(' ');
  if (spaceIdx === -1) return { dialCode: trimmed, digits: '' };
  return {
    dialCode: trimmed.substring(0, spaceIdx),
    digits: trimmed.substring(spaceIdx + 1).replace(/\D/g, ''),
  };
}
